refactor: move update_subscription to its own function

diff --git a/gh-notify b/gh-notify
--- a/gh-notify
+++ b/gh-notify
@@ -35,13 +35,13 @@ export WHITE_BOLD='\033[1m'
 export exclusion_string='XXX_BOGUS_STRING_THAT_SHOULD_NOT_EXIST_XXX'
 export filter_string=''
 export num_notifications='0'
-export only_participating_flag='false'
-export include_all_flag='false'
+export only_participating_flag=false
+export include_all_flag=false
 export preview_window_visibility='hidden'
 export python_executable=''
 # not necessarily to be exported, since they are not used in any child process
-print_static_flag='false'
-mark_read_flag='false'
+print_static_flag=false
+mark_read_flag=false
 update_subscription_url=''
 
 # ===================== basic functions =====================
@@ -112,12 +112,12 @@ while getopts 'e:f:n:u:pawhsr' flag; do
         e) exclusion_string="${OPTARG}" ;;
         f) filter_string="${OPTARG}" ;;
         n) num_notifications="${OPTARG}" ;;
-        p) only_participating_flag='true' ;;
+        p) only_participating_flag=true ;;
         u) update_subscription_url="${OPTARG}" ;;
-        a) include_all_flag='true' ;;
+        a) include_all_flag=true ;;
         w) preview_window_visibility='nohidden' ;;
-        s) print_static_flag='true' ;;
-        r) mark_read_flag='true' ;;
+        s) print_static_flag=true ;;
+        r) mark_read_flag=true ;;
         h)
             print_help_text
             exit 0
@@ -137,10 +137,8 @@ get_notifs() {
     if [ "$num_notifications" != "0" ]; then
         local_page_size=$num_notifications
     fi
-    printf >&2 "." # "marching ants" because sometimes this takes a bit.
-    # Use '-F/--field' to pass a variable that is a number, Boolean, or null. Use '-f/--raw-field'
-    # for other variables.
-    # Playground to test jq: https://jqplay.org/
+    # "marching ants" because sometimes this takes a bit.
+    printf >&2 "."
     gh api --header "$GH_REST_API_VERSION" --method GET notifications --cache=0s \
         --field per_page="$local_page_size" --field page="$page_num" \
         --field participating="$only_participating_flag" --field all="$include_all_flag" \
@@ -422,8 +420,7 @@ select_notif() {
     [[ -z $type ]] && exit 0
     case "$expected_key" in
         esc)
-            # quit with exit code 0; 'fzf' returns 130
-            # TODO: when updating to '0.38.0' use '--bind "esc:become:"'
+            # quit with exit code 0; 'fzf' returns 130 by default
             exit 0
             ;;
         ctrl-x)
@@ -461,12 +458,86 @@ check_version() {
     done
 }
 
+update_subscription() {
+    local graphql_query_resource=$'query ($url_input: URI!) {resource(url: $url_input) { ... on Subscribable { __typename id viewerCanSubscribe viewerSubscription }}}'
+    local graphql_mutation_update_subscription=$'mutation ($updated_state: SubscriptionState!, $node_id: ID!) { updateSubscription(input: {state: $updated_state, subscribableId: $node_id}) { subscribable { viewerSubscription }}}'
+    local graphql_query_subscribable=$'{ __type(name: "Subscribable") { possibleTypes { name }}}'
+    local updated_state update_text possibleTypes
+    if IFS=$'\t' read -r object_type node_id viewer_can_subscribe viewer_subscription < <(gh api graphql \
+        --raw-field url_input="$update_subscription_url" \
+        --raw-field query="$graphql_query_resource" \
+        --jq '.data.resource | map(.) | @tsv' 2>/dev/null); then
+        if [[ -z $object_type ]]; then
+            die "Your input appears to be an invalid URL: '$update_subscription_url'."
+        elif [[ $viewer_subscription != "SUBSCRIBED" && ! $viewer_can_subscribe ]]; then
+            die "You are not allowed to subscribe to this '$object_type'."
+        fi
+        # The enumValues for the 'SubscriptionState' are:
+        #"UNSUBSCRIBED" - "The User is only notified when participating or @mentioned."
+        #"SUBSCRIBED" - "The User is notified of all conversations."
+        #"IGNORED" - "The User is never notified."
+        case "$viewer_subscription" in
+            SUBSCRIBED)
+                updated_state="UNSUBSCRIBED"
+                update_text="Notifications disabled for this '$object_type'."
+                ;;
+            IGNORED | UNSUBSCRIBED)
+                updated_state="SUBSCRIBED"
+                update_text="Notifications enabled for this '$object_type'."
+                ;;
+            *)
+                # TODO: When a user makes a 'Custom' selection on what to watch in a repo via the
+                # Web UI. For instance, if a user chooses to only watch 'Releases', then
+                # 'viewer_subscription' becomes null for any URL associated with the entire repo and
+                # this error message is displayed. Currently, there is no workaround for this. Last
+                # checked: March '24.
+                die "The queried value for the current status is unknown: '$viewer_subscription'."
+                ;;
+        esac
+
+        # NOTE: For example, if you "UNSUBSCRIBE" from an Issue but you are still
+        # "SUBSCRIBED" to the Repository where the Issue resides, the Issue's
+        # subscription status is automatically set to "IGNORED" and can never be set
+        # to "UNSUBSCRIBED" as long as you are "SUBSCRIBED" to the Repository. This is
+        # a design decision by GitHub.
+        updated_state=$(gh api graphql --raw-field updated_state="$updated_state" \
+            --raw-field node_id="$node_id" \
+            --raw-field query="$graphql_mutation_update_subscription" \
+            --jq '.data.updateSubscription.subscribable.viewerSubscription') ||
+            die "Failed GraphQL mutation to update the subscription status."
+        echo "The list of all your subscriptions is only available via the Web UI."
+        printf "%bhttps://github.com/notifications/subscriptions%b\n\n" "$DARK_GRAY" "$NC"
+        printf "%b%s%b: %b%s%b\n" "$GREEN" "$updated_state" "$NC" "$WHITE_BOLD" "$update_text" "$NC"
+        printf "%b%s%b\n" "$DARK_GRAY" "$update_subscription_url" "$NC"
+        exit 0
+    else
+        possibleTypes=$(gh api graphql --raw-field query="$graphql_query_subscribable" \
+            --jq '.data.__type.possibleTypes | map(.name) | join(", ")' ||
+            die "Failed GraphQL query for possibleTypes.")
+        printf "The URL is not valid for subscription.\nValid subscription types: %b%s%b\n" "$WHITE_BOLD" "$possibleTypes" "$NC"
+        exit 1
+    fi
+}
+
 gh_notify() {
-    local python_version graphql_query_resource updated_state update_text
-    local graphql_mutation_update_subscription possibleTypes notifs
+    local python_version notifs
+
+    if ! type -p gh >/dev/null; then
+        die "install 'gh'"
+    fi
+
+    if [[ -n $update_subscription_url ]]; then
+        update_subscription
+    fi
+
+    if $mark_read_flag; then
+        mark_all_read "" || die "Failed to mark notifications as read."
+        echo "All notifications have been marked as read."
+        exit 0
+    fi
 
     # Bail early if we aren't static and pre-reqs aren't found
-    if [ $print_static_flag = "false" ]; then
+    if ! $print_static_flag; then
         for python_version in python python3; do
             if type -p $python_version >/dev/null; then
                 python_executable=$python_version
@@ -484,66 +555,11 @@ gh_notify() {
         check_version fzf "$MIN_FZF_VERSION"
     fi
 
-    if [[ -n $update_subscription_url ]]; then
-        graphql_query_resource=$'query ($url_input: URI!) {resource(url: $url_input) { ... on Subscribable { __typename id viewerCanSubscribe viewerSubscription }}}'
-        if IFS=$'\t' read -r object_type node_id viewer_can_subscribe viewer_subscription < <(gh api graphql \
-            --raw-field url_input="$update_subscription_url" --raw-field query="$graphql_query_resource" \
-            --jq '.data.resource | map(.) | @tsv' 2>/dev/null); then
-            if [[ $viewer_subscription != "SUBSCRIBED" && ! $viewer_can_subscribe ]]; then
-                die "You are not allowed to subscribe to this '$object_type'."
-            fi
-            case "$viewer_subscription" in
-                SUBSCRIBED)
-                    updated_state="UNSUBSCRIBED"
-                    update_text="Notifications disabled for this '$object_type'."
-                    ;;
-                IGNORED | UNSUBSCRIBED)
-                    updated_state="SUBSCRIBED"
-                    update_text="Notifications enabled for this '$object_type'."
-                    ;;
-                *)
-                    die "ERROR: the queried value for the current status is unknown: $viewer_subscription"
-                    ;;
-            esac
-            graphql_mutation_update_subscription=$'mutation ($updated_state: SubscriptionState!, $node_id: ID!) { updateSubscription(input: {state: $updated_state, subscribableId: $node_id}) { subscribable { viewerSubscription }}}'
-            # NOTE: For example, if you "UNSUBSCRIBE" from an Issue but you are still
-            # "SUBSCRIBED" to the Repository where the Issue resides, the Issue's
-            # subscription status is automatically set to "IGNORED" and can never be set
-            # to "UNSUBSCRIBED" as long as you are "SUBSCRIBED" to the Repository. This is
-            # a design decision by GitHub. The enumValues for the 'SubscriptionState' are:
-            # "UNSUBSCRIBED" - "The User is only notified when participating or @mentioned."
-            # "SUBSCRIBED" - "The User is notified of all conversations."
-            # "IGNORED" - "The User is never notified."
-            updated_state=$(gh api graphql --raw-field updated_state="$updated_state" \
-                --raw-field node_id="$node_id" \
-                --raw-field query="$graphql_mutation_update_subscription" \
-                --jq '.data.updateSubscription.subscribable.viewerSubscription') ||
-                die "Failed GraphQL mutation to update the subscription status."
-            echo "The list with all your subscriptions is only available via the Web UI."
-            printf "%bhttps://github.com/notifications/subscriptions%b\n\n" "$DARK_GRAY" "$NC"
-            printf "%b%s%b: %b%s%b\n" "$GREEN" "$updated_state" "$NC" "$WHITE_BOLD" "$update_text" "$NC"
-            printf "%b%s%b\n" "$DARK_GRAY" "$update_subscription_url" "$NC"
-            exit 0
-        else
-            possibleTypes=$(gh api graphql --raw-field query='{ __type(name: "Subscribable") { possibleTypes { name }}}' \
-                --jq '.data.__type.possibleTypes | map(.name) | join(", ")' ||
-                die "Failed GraphQL query for possibleTypes.")
-            printf "The URL is invalid to subscribe to.\nValid subscription types: %b%s%b\n" "$WHITE_BOLD" "$possibleTypes" "$NC"
-            exit 1
-        fi
-    fi
-
-    if [ "$mark_read_flag" = "true" ]; then
-        mark_all_read "" || die "Failed to mark notifications as read."
-        echo "All notifications have been marked as read."
-        exit 0
-    fi
-
     notifs="$(print_notifs)"
     if [ -z "$notifs" ]; then
         echo "$FINAL_MSG"
         exit 0
-    elif [ $print_static_flag = "false" ]; then
+    elif ! $print_static_flag; then
         select_notif "$notifs"
     else
         # remove unimportant elements from the static display
