chore: Improve notification marking and debugging

diff --git a/gh-notify b/gh-notify
--- a/gh-notify
+++ b/gh-notify
@@ -111,6 +111,11 @@ if $GH_NOTIFY_DEBUG_MODE; then
         die "Bash 4.1 or newer is required for debugging. Current version: ${BASH_VERSION}"
     fi
 
+    # Ensure fzf 0.51.0+ for '--with-shell' support.
+    MIN_FZF_VERSION="0.51.0"
+    # Ensure xtrace is enabled in all child processes started by 'fzf'.
+    FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS-} --with-shell \"$(which bash) -o xtrace -o nounset -o pipefail -c\""
+
     # Redirect xtrace output to a file
     exec 6>>"$gh_notify_debug_log"
     # Write the trace output to file descriptor 6
@@ -492,6 +497,10 @@ view_in_pager() {
     view_notification --all_comments "$1" | command less "${less_args[@]}" >/dev/tty
 }
 
+# Use this only when the list isn't filtered to avoid marking not displayed notifications as read.
+# Check if the 'fzf' query or '-e' (exclude) or '-f' (filter) flags were used by examining
+# the emptiness of '{q}' and any changes to `FINAL_MSG`, specifically if it remains "All caught up".
+# TODO: The 2nd check is hacky; seek a cleaner solution with minimal code addition.
 mark_all_read() {
     local iso_time
     IFS=' ' read -r iso_time _ <<<"$1"
@@ -506,14 +515,28 @@ mark_individual_read() {
     # succession. I didn't encounter any rate-limiting when testing with 100 unread notifications,
     # but further testing is needed to be sure.
 
-    # Running commands in the background of a script can cause it to hang, especially if the
-    # command outputs to stdout: https://tldp.org/LDP/abs/html/x9644.html#WAITHANG
+    declare -a array_threads=()
     while IFS=' ' read -r _ thread_id thread_state _; do
         if [[ $thread_state == "UNREAD" ]]; then
-            # https://docs.github.com/en/rest/activity/notifications#mark-a-thread-as-read
-            gh_rest_api --silent --method PATCH "notifications/threads/${thread_id}" &>/dev/null &
+            array_threads+=("$thread_id")
         fi
     done <"$1"
+
+    if ((${#array_threads[@]} > 1)); then
+        # If there ia large amount of threads to be processed the number of background job can put
+        # pressure on the PC and too many requests (>150) in short succession a rate limit by Github
+        # kicks in, so we run large numbers in batches of 30 with a short delay in between.
+        for ((i = 0; i < ${#array_threads[@]}; i += 30)); do
+            for j in "${array_threads[@]:i:30}"; do
+                # Running commands in the background of a script can cause it to hang, especially if
+                # the command outputs to stdout: https://tldp.org/LDP/abs/html/x9644.html#WAITHANG
+                gh_rest_api --silent --method PATCH "notifications/threads/${j}" &>/dev/null &
+            done
+            command sleep 0.3
+        done
+    elif ((${#array_threads[@]} == 1)); then
+        gh_rest_api --silent --method PATCH "notifications/threads/${array_threads[0]}" || die "Failed to mark notifications as read."
+    fi
 }
 
 select_notif() {
@@ -533,7 +556,7 @@ select_notif() {
             --ansi \
             --bind "${GH_NOTIFY_RESIZE_PREVIEW_KEY}:change-preview-window(75%:nohidden|75%:down:nohidden:border-top|nohidden)" \
             --bind "change:first" \
-            --bind "${GH_NOTIFY_MARK_ALL_READ_KEY}:select-all+execute-silent(if [[ -z {q} ]]; then mark_all_read {}; else mark_individual_read {+f}; fi)+reload:print_notifs || true" \
+            --bind "${GH_NOTIFY_MARK_ALL_READ_KEY}:select-all+execute-silent(if [[ -z {q} && \$FINAL_MSG =~ 'All caught up' ]]; then mark_all_read {}; else mark_individual_read {+f}; fi)+reload:print_notifs || true" \
             --bind "${GH_NOTIFY_OPEN_BROWSER_KEY}:execute-silent:open_in_browser {}" \
             --bind "${GH_NOTIFY_VIEW_DIFF_KEY}:toggle-preview+change-preview:if command grep -q PullRequest <<<{10}; then command gh pr diff {11} --repo {5}  | highlight_output; else view_notification {}; fi" \
             --bind "${GH_NOTIFY_VIEW_PATCH_KEY}:toggle-preview+change-preview:if command grep -q PullRequest <<<{10}; then command gh pr diff {11} --patch --repo {5} | highlight_output; else view_notification {}; fi" \
@@ -578,7 +601,8 @@ select_notif() {
         "${GH_NOTIFY_COMMENT_KEY}")
             if command grep -qE "Issue|PullRequest" <<<"$type"; then
                 command gh issue comment "$num" --repo "$repo_full_name"
-                mark_individual_read "$selected_line" || die "Failed to mark the notification as read."
+                # The function requires input in a file-like format
+                mark_individual_read <(echo "$selected_line")
             else
                 printf "Writing comments is only supported for %bIssues%b and %bPullRequests%b.\n" \
                     "$WHITE_BOLD" "$NC" "$WHITE_BOLD" "$NC"
@@ -714,8 +738,12 @@ main() {
     fi
 
     if $mark_read_flag; then
-        mark_all_read "" || die "Failed to mark notifications as read."
-        echo "All notifications have been marked as read."
+        if [[ $FINAL_MSG =~ 'All caught up' ]]; then
+            mark_all_read "" || die "Failed to mark notifications as read."
+            echo "All notifications have been marked as read."
+        else
+            die "Can't mark all notifications as read when either the '-e' or '-f' flag was used, as it would also mark notifications as read that are filtered out."
+        fi
         exit 0
     fi
 
