refactor: use the 'print_notifs' function to reload

diff --git a/gh-notify b/gh-notify
--- a/gh-notify
+++ b/gh-notify
@@ -11,25 +11,27 @@ export GH_FORCE_TTY=100%
 # Disable the gh pager
 export GH_PAGER="cat"
 
-die() {
-    echo ERROR: "$*" >&2
-    exit 1
-}
-
 # NotificationReason:
 # assign, author, comment, invitation, manual, mention, review_requested, security_alert, state_change, subscribed, team_mention, ci_activity
 # NotificationSubjectTypes:
 # CheckSuite, Commit, Discussion, Issue, PullRequest, Release, RepositoryVulnerabilityAlert, ...
 
-GREEN='\033[0;32m'
-NC='\033[0m'
-WHITE_BOLD='\033[1m'
+die() {
+    echo ERROR: "$*" >&2
+    exit 1
+}
+
+export GREEN='\033[0;32m'
+export NC='\033[0m'
+export WHITE_BOLD='\033[1m'
 
 # Create help message with colored text
 # IMPORTANT: Keep it synchronized with the README, but without the Examples.
 # IMPORTANT: Use an unquoted delimiter (EOF) to have the variables expanded.
-HELP_TEXT=$(
-    cat <<EOF
+print_help_text() {
+    local help_text
+    help_text=$(
+        cat <<EOF
 ${WHITE_BOLD}Usage${NC}
   gh notify [Flags]
 
@@ -62,40 +64,34 @@ ${WHITE_BOLD}Key Bindings fzf${NC}
 ${WHITE_BOLD}Example${NC}
     # Display the last 20 notifications
     gh notify -an 20
-EOF
-)
 
-include_all_flag='false'
-preview_window_visibility='hidden'
-only_participating_flag='false'
+EOF
+    )
+    echo -e "$help_text"
+}
+
+export exclusion_string='XXX_BOGUS_STRING_THAT_SHOULD_NOT_EXIST_XXX'
+export filter_string=''
+export num_notifications='0'
+export only_participating_flag='false'
+export include_all_flag='false'
+export preview_window_visibility='hidden'
+# not necessarily to be exported, since they are not used in any child process
 print_static_flag='false'
 mark_read_flag='false'
-num_notifications='0'
-exclusion_string='XXX_BOGUS_STRING_THAT_SHOULD_NOT_EXIST_XXX'
-filter_string=''
-# this flag outputs all items in the list that fzf receives as an input
-# it is not listed as an official flag in the docs, as it is used for reloading fzf only
-print_fzf_static_reload_flag='false'
 
-# https://github.com/mislav/gh-branch/blob/main/gh-branch#L105
-# this trick only works with the '-s' and '-z' flag
-reload_arguments="$0 $* -sz"
-
-while getopts 'e:f:n:pawhsrz' flag; do
+while getopts 'e:f:n:pawhsr' flag; do
     case "${flag}" in
-    n) num_notifications="${OPTARG}" ;;
     e) exclusion_string="${OPTARG}" ;;
     f) filter_string="${OPTARG}" ;;
+    n) num_notifications="${OPTARG}" ;;
+    p) only_participating_flag='true' ;;
     a) include_all_flag='true' ;;
     w) preview_window_visibility='nohidden' ;;
-    p) only_participating_flag='true' ;;
     s) print_static_flag='true' ;;
     r) mark_read_flag='true' ;;
-    z) print_fzf_static_reload_flag='true' ;;
     h)
-        # the -e option to enable the interpretation of backslash escapes,
-        # so that the ANSI escape sequences are correctly interpreted as color codes
-        echo -e "$HELP_TEXT"
+        print_help_text
         exit 0
         ;;
     *)
@@ -149,7 +145,7 @@ get_notifs() {
 
 print_notifs() {
     local all_notifs page_num page new_notifs graphql_query_discussion
-    all_notifs=""
+    all_notifs=''
     page_num=1
     graphql_query_discussion=$'query ($filter: String!) { search(query: $filter, type: DISCUSSION, first: 1) { nodes { ... on Discussion { number }}}}'
     while true; do
@@ -197,12 +193,23 @@ print_notifs() {
     # clear the dots we printed
     echo >&2 -e "\r\033[K"
 
-    echo "$all_notifs" | grep -v "$exclusion_string" | grep "$filter_string" | column -ts $'\t'
+    result=$(echo "$all_notifs" | grep -v "$exclusion_string" | grep "$filter_string" | column -ts $'\t')
+    # 'SHLVL' variable represents the nesting level of the current shell
+    # if its larger than 2, we assume to be in the 'fzf' reload function
+    if [[ -z "$result" && "$SHLVL" -gt 2 ]]; then
+        # TODO: exit fzf automatically if the list is empty after a reload
+        # it does work with '--bind "zero:become:"', but this only came with version '0.40.0'
+        # workaround, since fzf hides the first elements with '--with-nth 5..'
+        # if the list is empty on a reload, the message would be hidden, so ' \b' (backspace) is added
+        echo -e ' \b \b \b \bAll caught up!'
+    else
+        echo "$result"
+    fi
 }
 
 view_notification() {
     local date time repo type number
-    IFS=" " read -r _ _ _ _ date time repo type number _ <<<"$1"
+    IFS=' ' read -r _ _ _ _ date time repo type number _ <<<"$1"
     echo "[$date $time - $type]"
     case "$type" in
     Issue)
@@ -234,7 +241,7 @@ diff_pager() {
 
 open_in_browser() {
     local comment_number date time repo type number unhashed_num
-    IFS=" " read -r _ _ _ comment_number date time repo type number _ <<<"$1"
+    IFS=' ' read -r _ _ _ comment_number date time repo type number _ <<<"$1"
     unhashed_num=$(tr -d "#" <<<"$number")
     case "$type" in
     CheckSuite)
@@ -265,14 +272,14 @@ open_in_browser() {
 
 mark_all_read() {
     local iso_time
-    IFS=" " read -r iso_time _ <<<"$1"
+    IFS=' ' read -r iso_time _ <<<"$1"
     gh api --silent --header "$GH_REST_API_VERSION" --method PUT notifications \
         --raw-field last_read_at="$iso_time" --field read=true
 }
 
 mark_individual_read() {
     local thread_id thread_state
-    IFS=" " read -r _ thread_id thread_state _ <<<"$1"
+    IFS=' ' read -r _ thread_id thread_state _ <<<"$1"
     if [ "$thread_state" = UNREAD ]; then
         gh api --silent --header "$GH_REST_API_VERSION" --method PATCH "notifications/threads/${thread_id}"
     fi
@@ -283,8 +290,11 @@ select_notif() {
     # make functions available in child processes
     # 'SHELL="bash"' is needed, as it would typical fail on macOS that uses,
     # 'zsh' by default, which doesn't support exporting functions this way
+    export -f print_help_text print_notifs get_notifs
     export -f diff_pager open_in_browser view_notification
     export -f mark_all_read mark_individual_read
+    # The 'die' function is not exported because 'fzf' warns you about the error in
+    # a failed 'print_notifs' call, but does not display the message.
 
     # See the man page (man fzf) for an explanation of the arguments.
     # '--print-query' and '--delimiter' are not strictly needed here,
@@ -299,26 +309,25 @@ select_notif() {
             --header "? help · esc quit" --color "header:green:italic:dim" \
             --prompt "GitHub Notifications > " --color "prompt:80,info:40" \
             --bind "change:first" \
-            --bind "?:toggle-preview+change-preview:echo -e '$HELP_TEXT'" \
+            --bind "?:toggle-preview+change-preview:print_help_text" \
             --bind "ctrl-b:execute-silent:open_in_browser {}" \
             --bind "ctrl-d:toggle-preview+change-preview:if grep -q PullRequest <<<{8}; then gh pr diff {9} --repo {7}  | diff_pager; else view_notification {}; fi" \
             --bind "ctrl-p:toggle-preview+change-preview:if grep -q PullRequest <<<{8}; then gh pr diff {9} --patch --repo {7} | diff_pager; else view_notification {}; fi" \
-            --bind "ctrl-r:execute-silent(mark_all_read {})+reload:$reload_arguments || true" \
-            --bind "ctrl-t:execute-silent(mark_individual_read {})+reload:$reload_arguments || true" \
+            --bind "ctrl-r:execute-silent(mark_all_read {})+reload:print_notifs || true" \
+            --bind "ctrl-t:execute-silent(mark_individual_read {})+reload:print_notifs || true" \
             --bind "tab:toggle-preview+change-preview:view_notification {}" \
             --bind "btab:change-preview-window(75%:nohidden|75%:down:nohidden:border-top|nohidden)" \
             --preview-window wrap:"$preview_window_visibility":50%:right:border-left \
             --preview "view_notification {}" \
             --expect "enter,esc,ctrl-x"
     )
-
     # actions that close fzf are defined below
     # 1st line ('--print-query'): the input query string
     # 2nd line ('--expect'): the actual key
     # 3rd line: the selected line when the user pressed the key
     expected_key="$(sed '1d;3d' <<<"$output")"
     selected_line="$(sed '1d;2d' <<<"$output")"
-    IFS=" " read -r _ thread_id thread_state _ _ _ repo type num _ <<<"$selected_line"
+    IFS=' ' read -r _ thread_id thread_state _ _ _ repo type num _ <<<"$selected_line"
     [[ -z "$type" ]] && exit 0
     case "$expected_key" in
     enter)
@@ -327,6 +336,7 @@ select_notif() {
         ;;
     esc)
         # quit with exit code 0; 'fzf' returns 130
+        # TODO: when updating to '0.38.0' use '--bind "esc:become:"'
         exit 0
         ;;
     ctrl-x)
@@ -357,10 +367,7 @@ version() {
 
 notifs="$(print_notifs)"
 if [[ -z "$notifs" ]]; then
-    # TODO: exit fzf automatically if the list is empty after a reload
-    # workaround, since fzf hides the first elements with '--with-nth'
-    # if the list is empty on a reload, the message would be hidden, so ' \b' (backspace) is added
-    echo -e ' \b \b \b \bAll caught up!'
+    echo "All caught up!"
     exit 0
 elif [[ $print_static_flag == "false" ]]; then
     if ! type -p fzf >/dev/null; then
@@ -375,10 +382,6 @@ elif [[ $print_static_flag == "false" ]]; then
         echo "'Python' is used to open some URLs with 'ctrl-b'" >&2
     fi
     select_notif "$notifs"
-elif [[ $print_fzf_static_reload_flag == "true" ]]; then
-    # this is used as input for fzf when reloading,
-    # it should not be truncated, as this would affect the functionality of fzf
-    echo "$notifs"
 else
     # remove unimportant elements from the static display
     # '[[:blank:]]' matches horizontal whitespace characters (spaces/ tabs)
