docs: add a warning when 'python' executable can't be found

diff --git a/gh-notify b/gh-notify
--- a/gh-notify
+++ b/gh-notify
@@ -290,15 +290,18 @@ if [[ -z "$notifs" ]]; then
     exit 0
 elif [[ $print_static_flag == "false" ]]; then
     if ! type -p fzf >/dev/null; then
-        echo "error: install \`fzf\` or use the -s flag" >&2
+        echo "error: install 'fzf' or use the -s flag" >&2
         exit 1
     fi
     USER_FZF_VERSION="$(fzf --version)"
     if [ "$(version $MIN_FZF_VERSION)" -gt "$(version "$USER_FZF_VERSION")" ]; then
-        echo "Error: \`fzf\` was found, but it is too old".
-        echo "Your \`fzf\` version is: $USER_FZF_VERSION".
-        echo "Minimum required \`fzf\` version is: $MIN_FZF_VERSION"
+        echo "Error: 'fzf' was found, but it is too old".
+        echo "Your 'fzf' version is: $USER_FZF_VERSION".
+        echo "Minimum required 'fzf' version is: $MIN_FZF_VERSION"
         exit 1
+    fi
+    if ! type -p python >/dev/null; then
+        echo "warning: 'python' was not found, it is recommended to install it, which is used to open some URLs with ctrl-b" >&2
     fi
     select_notif "$notifs"
 elif [[ $print_fzf_static_reload_flag == "true" ]]; then
