fix: Update notification fetching logic for pagination

diff --git a/gh-notify b/gh-notify
--- a/gh-notify
+++ b/gh-notify
@@ -19,6 +19,8 @@ MIN_FZF_VERSION="0.29.0"
 # export variables for use in child processes
 # https://docs.github.com/en/rest/overview/api-versions
 export GH_REST_API_VERSION="X-GitHub-Api-Version:2022-11-28"
+# The maximum number of notifications per page (set by GitHub)
+export MAX_PER_PAGE_LIMIT=50
 # Enable terminal-style output even when the output is redirected.
 export GH_FORCE_TTY=1
 
@@ -69,7 +71,7 @@ export WHITE_BOLD='\033[1m'
 
 export exclusion_string='XXX_BOGUS_STRING_THAT_SHOULD_NOT_EXIST_XXX'
 export filter_string=''
-export num_notifications='0'
+export num_notifications=0
 export only_participating_flag=false
 export include_all_flag=false
 export preview_window_visibility='hidden'
@@ -166,16 +168,12 @@ done
 # ===================== helper functions ==========================
 
 get_notifs() {
-    local page_num local_page_size
-    page_num="${1:-1}"
-    local_page_size=100
-    if [ "$num_notifications" != "0" ]; then
-        local_page_size=$num_notifications
-    fi
+    local page_num="$1"
+
     # "marching ants" because sometimes this takes a bit.
     printf >&2 "."
     gh api --header "$GH_REST_API_VERSION" --method GET notifications --cache=0s \
-        --field per_page="$local_page_size" --field page="$page_num" \
+        --field per_page="$MAX_PER_PAGE_LIMIT" --field page="$page_num" \
         --field participating="$only_participating_flag" --field all="$include_all_flag" \
         --jq \
         $'def colors:
@@ -235,22 +233,37 @@ get_notifs() {
 }
 
 print_notifs() {
-    local all_notifs page_num page new_notifs result
-    all_notifs=''
-    page_num=1
-    while true; do
-        page=$(get_notifs $page_num) || die "Failed to get notifications."
-        if [ -z "$page" ]; then
-            break
+    local local_page_size page new_notifs result
+    local page_num=1
+    local total_requested="$num_notifications" # Total number of notifications requested
+    local fetched_count=0                      # A counter for the number of fetched notifications
+    local all_notifs=""
+    while :; do
+        local_page_size=$((total_requested - fetched_count > MAX_PER_PAGE_LIMIT ? \
+            MAX_PER_PAGE_LIMIT : total_requested - fetched_count))
+        page=$(get_notifs "$page_num") || die "Failed to get notifications."
+        [[ -z $page ]] && break
+
+        page_num=$((page_num + 1))
+        # On each run, we can fetch up to 50 notifications. If a user requested 56, we can't specify
+        # 6 notifications 'per_page' for page number 2. This would incorrectly return notifications
+        # 6-11 from page number 1, which we already have. Therefore, if a user requests 56
+        # notifications, we need to call the REST API twice with the maximum 'per_page' size and
+        # then truncate the second page accordingly.
+        if ((total_requested > 0)) && ((local_page_size < MAX_PER_PAGE_LIMIT)); then
+            page=$(head -n "$local_page_size" <<<"$page")
         else
-            page_num=$((page_num + 1))
+            local_page_size=$(sed -n '$=' <<<"$page")
         fi
+
         new_notifs=$(process_page "$page") || die "Failed to process page."
         all_notifs="${all_notifs}${new_notifs}"
-        # this is going to be a bit funky.
-        # if you specify a number larger than 100
-        # GitHub will ignore it and give you only 100
-        [[ $num_notifications != "0" ]] && break
+        fetched_count=$((fetched_count + local_page_size))
+        # If the number of fetched results equals the number of requested results, or if the number
+        # of items retrieved in this round is less than the maximum per page limit, we stop.
+        if ((fetched_count == total_requested)) || ((local_page_size < MAX_PER_PAGE_LIMIT)); then
+            break
+        fi
     done
     # clear the dots we printed
     echo >&2 -ne "\r\033[K"
